apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: tetrate
  tenant: marketing
  workspace: marketing-ws
  name: blogger-gw
spec:
  displayName: blogger-gateway
  namespaceSelector:
    names:
      - "<cluster>/tsb-cz-demo"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
Metadata:
  organization: tetrate
  tenant: marketing
  workspace: marketing-ws
  name: blogger-traffic
spec:
  displayName: blogger-traffic-group
  namespaceSelector:
    names:
      - "<cluster>/tsb-cz-demo"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
Metadata:
  organization: tetrate
  tenant: marketing
  workspace: marketing-ws
  name: blogger-security
spec:
  displayName: blogger-security-group
  namespaceSelector:
    names:
      - "<cluster>/tsb-cz-demo"
  configMode: BRIDGED